name: OSV-Scanner

on:
  pull_request:
    branches: [feature/windows-setup-guide]
  merge_group:
    branches: [feature/windows-setup-guide]
  push:
    branches: [feature/windows-setup-guide]
  schedule:
    - cron: "30 12 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Run OSV-Scanner
        continue-on-error: true
        uses: google/osv-scanner-action/osv-scanner-action@7f58dd6750d78fc29a900ba64b1a0f946f62fba4 # v2.6.0
        with:
          scan-args: |-
            --recursive
            ./
