name: OSV-Scanner

on:
  pull_request:
    branches: [feature/windows-setup-guide]
  merge_group:
    branches: [feature/windows-setup-guide]
  push:
    branches: [feature/windows-setup-guide]
  schedule:
    - cron: "30 12 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  scan-pr:
    if: github.event_name == 'pull_request' || github.event_name == 'merge_group'
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@a345acffa64b0eaede81a3d9aae6141214d9c8fc # v2.6.0
    with:
      upload-sarif: false
    permissions:
      contents: read
      actions: read

  scan-scheduled:
    if: github.event_name != 'pull_request' && github.event_name != 'merge_group'
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@a345acffa64b0eaede81a3d9aae6141214d9c8fc # v2.6.0
    with:
      fail-on-vuln: false
      upload-sarif: false
    permissions:
      contents: read
      actions: read
